import type { NextPage } from "next";
import Head from "next/head";
import { About } from "../components/about/About";
import { Header } from "../components/header/Header";
import { Hero } from "../components/hero/Hero";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Olaiya Basit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <About />
    </div>
  );
};

export default Home;
